name: Release Build

on:
  push:
    tags:
      - 'v*' # 推送 v 开头的tag时触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [linux/amd64, linux/arm64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Build binary
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: build --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release assets
      run: |
        # 为每个平台创建压缩包
        for platform in linux-amd64 linux-arm64; do
          mkdir -p dist/$platform
          cp m-ui dist/$platform/
          tar -czf dist/m-ui-$platform.tar.gz -C dist/$platform m-ui
        done

    - name: Upload release assets
      uses: actions/upload-artifact@v3
      with:
        name: release-assets
        path: dist/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download release assets
      uses: actions/download-artifact@v3
      with:
        name: release-assets
        path: dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}